spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081
resilience4j:
  circuitbreaker:
    configs:
      pizzaDb:
        registerHealthIndicator: true
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 1s
        failureRateThreshold: 100
